name: Terraform Destroy

on:
  workflow_dispatch:

jobs:
  destroy:
    name: Destroy Terraform
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.8.4
          cli_config_credentials_token: ${{ secrets.TF_API_TOKEN }}

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: eu-west-2

      - name: Switch DNS to Maintenance Page
        run: |
          ZONE_ID=$(aws route53 list-hosted-zones-by-name \
            --dns-name prasadcloud.com \
            --query 'HostedZones[0].Id' \
            --output text | cut -d'/' -f3)

          aws route53 change-resource-record-sets \
            --hosted-zone-id $ZONE_ID \
            --change-batch '{
              "Changes": [{
                "Action": "UPSERT",
                "ResourceRecordSet": {
                  "Name": "singingai.prasadcloud.com",
                  "Type": "CNAME",
                  "TTL": 60,
                  "ResourceRecords": [{
                    "Value": "singingai-fallback-prasadcloud.s3-website.eu-west-2.amazonaws.com"
                  }]
                }
              }]
            }'
          echo "DNS switched to maintenance page"
          echo "Waiting 60 seconds for DNS propagation..."
          sleep 60

      - name: Terraform Init
        run: terraform init

      - name: Terraform Destroy
        run: terraform destroy -auto-approve -lock-timeout=60s
        timeout-minutes: 30
        env:
          TF_VAR_db_password: ${{ secrets.TF_VAR_DB_PASSWORD }}
          TF_VAR_my_ip: ${{ secrets.TF_VAR_MY_IP }}
          TF_VAR_private_key_path: ${{ secrets.TF_VAR_PRIVATE_KEY_PATH }}
          TF_VAR_groq_api_key: ${{ secrets.TF_VAR_GROQ_API_KEY }}
          TF_VAR_google_client_id: ${{ secrets.TF_VAR_GOOGLE_CLIENT_ID }}
          TF_VAR_google_client_secret: ${{ secrets.TF_VAR_GOOGLE_CLIENT_SECRET }}
          TF_VAR_session_secret: ${{ secrets.TF_VAR_SESSION_SECRET }}