name: Terraform Deployment

on:
  push:
    branches:
      - main

jobs:
  deploy:
    name: Deploy Terraform
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.8.4  # Use the required Terraform version
          cli_config_credentials_token: ${{ secrets.TF_API_TOKEN }}

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: eu-west-2  # Replace with your AWS region

      - name: Setup Terraform Cloud Credentials
        run: |
          echo "credentials \"app.terraform.io\" { token = \"${{ secrets.TF_API_TOKEN }}\" }" > ~/.terraformrc

      - name: Display Terraform Configuration
        run: cat ~/.terraformrc

      - name: Initialize Terraform
        run: terraform init -input=false -no-color
        env:
          TF_API_TOKEN: ${{ secrets.TF_API_TOKEN }}

      - name: Validate Terraform Configuration
        run: terraform validate -no-color
        env:
          TF_API_TOKEN: ${{ secrets.TF_API_TOKEN }}

      - name: Plan Terraform Changes
        run: terraform plan -input=false -no-color
        env:
          TF_API_TOKEN: ${{ secrets.TF_API_TOKEN }}
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          TF_VAR_db_password: ${{ secrets.TF_VAR_DB_PASSWORD }}
          TF_VAR_my_ip: ${{ secrets.TF_VAR_MY_IP }}
          TF_VAR_private_key_path: ${{ secrets.TF_VAR_PRIVATE_KEY_PATH }}
          TF_VAR_groq_api_key: ${{ secrets.TF_VAR_GROQ_API_KEY }}
          TF_VAR_google_client_id: ${{ secrets.TF_VAR_GOOGLE_CLIENT_ID }}
          TF_VAR_google_client_secret: ${{ secrets.TF_VAR_GOOGLE_CLIENT_SECRET }}
          TF_VAR_session_secret: ${{ secrets.TF_VAR_SESSION_SECRET }}

      - name: Terraform Apply
        run: terraform apply -auto-approve
        env:
          TF_API_TOKEN: ${{ secrets.TF_API_TOKEN }}
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          TF_VAR_db_password: ${{ secrets.TF_VAR_DB_PASSWORD }}
          TF_VAR_my_ip: ${{ secrets.TF_VAR_MY_IP }}
          TF_VAR_private_key_path: ${{ secrets.TF_VAR_PRIVATE_KEY_PATH }}
          TF_VAR_groq_api_key: ${{ secrets.TF_VAR_GROQ_API_KEY }}
          TF_VAR_google_client_id: ${{ secrets.TF_VAR_GOOGLE_CLIENT_ID }}
          TF_VAR_google_client_secret: ${{ secrets.TF_VAR_GOOGLE_CLIENT_SECRET }}
          TF_VAR_session_secret: ${{ secrets.TF_VAR_SESSION_SECRET }}